name: 🐞 Bug Report
description: Report something that isn't working
labels: "bug"
body:
  - type: input
    attributes:
      label: Obsidian version
      placeholder: e.g., 1.11.7
    validations:
      required: true
  - type: input
    attributes:
      label: Obsidian installer version
      placeholder: e.g., 1.11.7
    validations:
      required: true
  - type: input
    attributes:
      label: Baseline version
      placeholder: e.g., 3.2.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: macOS 26.3, Windows 11 25H2, iOS 26.3, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: What is not working correctly?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How to recreate this issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to see?
  - type: textarea
    attributes:
      label: Proposed solution
      description: Do you have suggestions on how to fix this?
